--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ParoxityTeam/Commando
build-by-default: true
branches:
- master
- PM-4.0
projects:
  Commando:
    model: virion
    type: library
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.0.1
...
